# Progressive Quality Gates Configuration
# Autonomous SDLC Quality Enhancement System

version: "1.0"
description: "Progressive quality gates configuration for HIPAA Compliance Summarizer"

# Global settings
global:
  auto_retry: true
  max_retries: 2
  parallel_execution: true
  report_format: "json"
  notification_on_failure: true

# Quality gate configurations
gates:
  syntax:
    enabled: true
    threshold: 1.0
    auto_fix: true
    timeout: 300
    severity: "error"
    tools:
      - "ruff"
    rules:
      - "no_syntax_errors"
      - "pep8_compliance"
    
  testing:
    enabled: true
    threshold: 0.85
    auto_fix: false
    timeout: 600
    severity: "error"
    tools:
      - "pytest"
    rules:
      - "min_coverage_85_percent"
      - "all_tests_pass"
      - "no_test_failures"
    coverage:
      minimum: 85
      fail_under: 80
      exclude:
        - "*/tests/*"
        - "*/__pycache__/*"
    
  security:
    enabled: true
    threshold: 0.9
    auto_fix: true
    timeout: 300
    severity: "error"
    tools:
      - "bandit"
      - "safety"
    rules:
      - "no_high_severity_vulnerabilities"
      - "encrypt_phi_data"
      - "secure_authentication"
      - "audit_logging_enabled"
    hipaa_requirements:
      - "phi_encryption_at_rest"
      - "access_controls"
      - "audit_trails"
      - "data_minimization"
    
  performance:
    enabled: true
    threshold: 0.8
    auto_fix: true
    timeout: 900
    severity: "warning"
    tools:
      - "custom_performance_tests"
    rules:
      - "response_time_under_2s"
      - "memory_usage_optimized"
      - "cpu_usage_under_80_percent"
    benchmarks:
      document_processing: "< 10s per document"
      batch_processing: "> 400 documents/hour"
      memory_usage: "< 2GB peak"
    
  compliance:
    enabled: true
    threshold: 0.95
    auto_fix: false
    timeout: 180
    severity: "error"
    standards:
      - "HIPAA"
      - "GDPR"
      - "SOC2"
    rules:
      - "hipaa_config_present"
      - "phi_detection_accuracy_98_percent"
      - "audit_logging_comprehensive"
      - "data_retention_policies"
      - "access_control_implemented"
    required_files:
      - "config/hipaa_config.yml"
      - "SECURITY.md"
      - "docs/hipaa-compliance.md"
    
  documentation:
    enabled: true
    threshold: 0.7
    auto_fix: true
    timeout: 120
    severity: "warning"
    rules:
      - "readme_present"
      - "api_documentation_complete"
      - "code_documented_70_percent"
      - "architecture_documented"
    required_docs:
      - "README.md"
      - "ARCHITECTURE.md"
      - "API_DOCUMENTATION.md"
      - "CONTRIBUTING.md"
      - "docs/hipaa-compliance.md"
    
  dependency:
    enabled: true
    threshold: 0.9
    auto_fix: true
    timeout: 300
    severity: "error"
    tools:
      - "pip-audit"
      - "safety"
    rules:
      - "no_known_vulnerabilities"
      - "dependencies_up_to_date"
      - "no_deprecated_packages"
    auto_update:
      security_patches: true
      minor_versions: false
      major_versions: false

# Remediation strategies
remediation:
  syntax:
    - command: "ruff check --fix"
    - description: "Auto-fix syntax and style issues"
  
  security:
    - command: "pip-audit --fix"
    - description: "Update vulnerable dependencies"
    - manual_steps:
      - "Review security scan results"
      - "Implement additional security controls"
      - "Update encryption standards"
  
  testing:
    - description: "Increase test coverage"
    - suggestions:
      - "Add unit tests for new functions"
      - "Implement integration tests"
      - "Add performance test cases"
  
  performance:
    - description: "Optimize performance bottlenecks"
    - suggestions:
      - "Profile slow operations"
      - "Implement caching strategies"
      - "Optimize database queries"
  
  compliance:
    - description: "Address compliance gaps"
    - requirements:
      - "Ensure HIPAA configuration complete"
      - "Implement missing security controls"
      - "Update compliance documentation"
  
  documentation:
    - description: "Improve documentation coverage"
    - auto_fix:
      - "Generate missing docstrings"
      - "Update README.md"
    - manual_steps:
      - "Review and update architecture docs"
      - "Add API examples"

# Notification settings
notifications:
  on_failure:
    enabled: true
    channels:
      - "console"
      - "file"
    severity_levels:
      - "error"
      - "warning"
  
  on_success:
    enabled: true
    channels:
      - "console"
    summary: true

# Reporting settings
reporting:
  format: "json"
  output_file: "quality_gates_report.json"
  history_retention: 30  # days
  include_details: true
  generate_trends: true
  
# Progressive enhancement settings
progressive:
  generations:
    generation_1:
      focus: "basic_functionality"
      required_gates: ["syntax", "testing"]
      threshold: 0.8
    
    generation_2:
      focus: "reliability_security"
      required_gates: ["syntax", "testing", "security", "compliance"]
      threshold: 0.85
    
    generation_3:
      focus: "performance_scaling"
      required_gates: ["syntax", "testing", "security", "performance", "compliance"]
      threshold: 0.9
    
    generation_4:
      focus: "production_ready"
      required_gates: ["syntax", "testing", "security", "performance", "compliance", "documentation", "dependency"]
      threshold: 0.95

# Advanced features
advanced:
  ai_assisted_fixes: true
  predictive_quality: true
  trend_analysis: true
  custom_rules: true
  integration_hooks: true