name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install ruff bandit coverage pip-audit pre-commit
      - name: Pre-commit
        run: pre-commit run --all-files
      - name: Lint
        run: ruff check .
      - name: Security Scan
        run: bandit -r src
      - name: Run Tests
        run: pytest -n auto --cov=hipaa_compliance_summarizer --cov-report=xml --cov-report=term -q
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
      - name: Vulnerability Scan
        run: pip-audit -r requirements.txt
