name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install ruff bandit coverage pip-audit
      - name: Lint
        run: ruff check .
      - name: Security Scan
        run: bandit -r src
      - name: Run Tests
        run: coverage run -m pytest -q
      - name: Coverage Report
        run: |
          coverage xml
          coverage report -m
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
      - name: Vulnerability Scan
        run: pip-audit -r requirements.txt
